### PR TITLE
Update to 0.6.0

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
@conda-forge-admin, please update team

**Comment by nicoddemus** [comment]
@jakirkham do you know if the bot is online? It seems the team for this feedstock has not been updated.

**Comment by jakirkham** [comment]
IDK. Took a brief look (kind of on holiday ATM), but not totally sure why it didn't work. Could merge though if you would like?

**Comment by nicoddemus** [comment]
Please do merge, thanks! Enjoy your holiday! 😁

**Comment by jakirkham** [comment]
Merged. Thanks. Will do. 😄

**Comment by jakirkham** [comment]
FWIW looks like merging fixed it. So you should now have permission, @nicoddemus.

**Comment by jakirkham** [comment]
When you have a chance @isuruf, could you please take a look at the command bot to make sure it is behaving ok? Particularly the team update portion. It looks like we typed the command ok and the webhook says everything was ok. Retriggering it manually had no effect and the logs were basically clean of anything. So not totally sure what happened here.

**Comment by isuruf** [comment]
@jakirkham, I don't think update team command works in PRs. I think I added it for only issues.

**Comment by isuruf** [comment]
See https://conda-forge.org/docs/webservice.html#conda-forge-admin-please-update-team only for issues

**Comment by nicoddemus** [comment]
@isuruf thanks for the clarification!

**Comment by jakirkham** [comment]
Ah ok. Sorry for the misunderstanding.

Guess we could add it for PRs. Have no strong feelings on it though.

**Pull request merged**
