### PR TITLE
Fix recipe

### PR DESCRIPTION
**Pull request by chrisburr**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by chrisburr** [comment]
@conda-forge-admin, please rerender

**Comment by chrisburr** [comment]
I fairly sure this will be automatically added to the Python 3.8 migration after this PR is merged. If it isn't, ping me and I'll migrate it manually.

**Comment by duncanmmacleod** [comment]
@chrisburr, I think this is still needed, can you rebase and then merge?

**Comment by chrisburr** [comment]
I can rebased (and have) but I don't have the permissions needed to merge merge

The Travis failure is https://github.com/conda-forge/status/issues/79 and shouldn't block this from being merged.

**Comment by nicoddemus** [comment]
@conda-forge admin, please rerender

**Comment by nicoddemus** [comment]
I've updated the recipe to build everything on Azure. 👍 

I will merge it right after this passes.

**Comment by nicoddemus** [comment]
@conda-forge-admin, please rerender

**Comment by nicoddemus** [comment]
@conda-forge-admin, please rerender

**Comment by chrisburr** [comment]
@nicoddemus Ready to go!

For future reference, you can now add the "automerge" label to automatically merge when the CI passes

**Comment by nicoddemus** [comment]
Thanks @chrisburr!

> For future reference, you can now add the "automerge" label to automatically merge when the CI passes

I'm a bit wary of that, because it will auto merge even if dependency pins change upstream (which means we should also update the pins on the recipe), which leads to technically broken conda packages.

**Comment by nicoddemus** [comment]
Ahh sorry, misunderstood you! I thought you meant enabling "auto merge" feature on the repository.

Didn't know about the label, thanks!

**Pull request merged**
