### PR TITLE
Update to 0.5.1 release and add myself as maintainer

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
@JohnGreeley this seems now ready to be merged. 👍

**Comment by jakirkham** [comment]
Any thoughts on converting this into a noarch Python package?

**Comment by nicoddemus** [comment]
@jakirkham definitely. Closing this in favor of #4.

**Comment by nicoddemus** [comment]
@jakirkham I'm definitely doing this for all the packages I maintain, btw (when I update them). Much simpler and straightforward, you guys did an amazing job.

**Pull request closed without merging**
